name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-version: [22.x, 24.x]
        runs-on: ${{ matrix.os }}
        permissions:
            contents: read
        timeout-minutes: 15
        steps:
            - name: Checkout code repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
              with:
                  fetch-depth: 0
            - name: Setup pnpm
              uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
              with:
                  run_install: true
            - name: Cache pnpm modules
              uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
              env:
                  cache-name: cache-pnpm-modules
              with:
                  path: ~/.pnpm-store
                  key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ matrix.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install pnpm modules
              run: pnpm install
            - name: Run build
              run: pnpm run build
            - name: Run linting
              run: pnpm run lint
            - name: Run unit tests
              run: pnpm run test
            - name: Run SonarCloud scan
              if: matrix.os == 'ubuntu-latest' && matrix.node-version == '22.x'
              uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
              env:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_PAT }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    version:
        # Run version job only on pushes to the main branch. The job depends on completion of the build job.
        if: github.repository == 'SAP/guided-answers-extension' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        permissions:
            contents: read
        needs: build
        outputs:
            changes: ${{ steps.changesetVersion.outputs.changes }} # map step output to job output
        steps:
            - name: Checkout code repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
              with:
                  fetch-depth: 0
                  token: ${{ secrets.ACCESS_PAT }}
            - name: Setup pnpm
              uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
              with:
                  run_install: true
            - name: Cache pnpm modules
              uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
              env:
                  cache-name: cache-pnpm-modules
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
            - name: Use Node.js 22.x
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
              with:
                  node-version: 22.x
            - name: Install pnpm modules
              run: pnpm install
            - name: Apply changesets
              id: changesetVersion
              run: |
                  echo "changes=$(pnpm ci:version 2>&1 | grep -q 'No unreleased changesets found' && echo 'false' || echo 'true')" >> $GITHUB_OUTPUT
                  git status
            - name: Commit and push changes
              if: steps.changesetVersion.outputs.changes == 'true'
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git status
                  git add -A
                  git status
                  git commit -m "chore: apply latest changesets" --no-verify || echo "No changesets found"
                  git log --pretty=oneline | head -n 10
                  git push
    release:
        # Run release job only on pushes to the main branch. The job depends on completion of the build job.
        # This job needs to run after the version job commit has been merged - so check if that step returns 'false'
        if: github.repository == 'SAP/guided-answers-extension' && github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.version.outputs.changes == 'false'
        runs-on: ubuntu-latest
        permissions:
            contents: write
        needs: version
        steps:
            - name: Checkout code repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
            - name: Setup pnpm
              uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
              with:
                  run_install: true
            - name: Cache pnpm modules
              uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
              env:
                  cache-name: cache-pnpm-modules
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
            - name: Use Node.js 22.x
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
              with:
                  node-version: 22.x
            - name: Install pnpm modules
              run: pnpm install
            - name: Replace placeholder with instrumentation key
              uses: jacobtomlinson/gha-find-replace@f1069b438f125e5395d84d1c6fd3b559a7880cb5 # v3.0.5
              with:
                  include: packages/ide-extension/src/telemetry/telemetry.ts
                  find: 'ApplicationInsightsInstrumentationKeyPLACEH0LDER'
                  replace: ${{ secrets.INSTRUMENTATION_KEY }}
                  regex: false
            - name: Run build
              run: pnpm run build
            - name: Package vsix
              run: pnpm run ide-ext:package
            - name: Get version number from /packages/ide-extension/package.json
              id: package-version
              uses: martinbeentjes/npm-get-version-action@3cf273023a0dda27efcd3164bdfb51908dd46a5b # v1.3.1
              with:
                  path: packages/ide-extension
            - name: Read last entry of changelog
              run: |
                  echo "lastChangelogEntry<<END_CHANGEL0G_ENTRY" >> $GITHUB_ENV
                  node -e 'require(`changelog-parser`)(`./packages/ide-extension/CHANGELOG.md`).then((c)=>console.log(c?.versions?.[0]?.body || `See CHANGELOG.md for details`))' >> $GITHUB_ENV
                  echo "END_CHANGEL0G_ENTRY" >> $GITHUB_ENV
            - name: Create Github Release
              uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
              with:
                  body: ${{ env.lastChangelogEntry }}
                  draft: false
                  files: packages/ide-extension/sap-guided-answers*.vsix
                  fail_on_unmatched_files: true
                  tag_name: sap-guided-answers-extension@${{ steps.package-version.outputs.current-version}}
